contact_links:
  - name: ðŸ¤” I have a question
    url: https://github.com/fief-dev/fief/discussions/new?category=q-a
    about: If you have any question about Fief that's not clearly a bug, please open a discussion first.
